columns_colors_dict = {
    'l.p': ['A933FF', 'C16FFD'],
    # 'Data dodania': [,],
    # 'Data wygaśnięcia': [,],
    # 'Link': [,],
    # 'Link2': [,],
    # 'Adres': [,],
    # 'Dzielnica': [,],
    # 'podzielnica': [,],
    # 'Sprzedane?': [,],
    # 'Pośrednik?': [,],
    # 'Telefon': [,],
    # 'Cena': [,],
    # 'Cena/m2': [,],
    # 'm2': [,],
    # 'Pokoje': [,],
    # 'Piętro': [,],
    # 'Rodzaj mieszkania': [,],
    # 'Min': [,],
    # 'Min/m2': [,],
    # 'Data obejrzenia': [,],
    # 'Data ostatniego kontaktu': [,],
    # 'Notatka': [,],
    # 'Tabela dzwonienie': [,],
    # 'm2_category': [,],
    # 'Cena/m2_mean_Dzielnica': [,],
    # 'maksymalna_cena_Dzielnica': [,],
    # 'additional_profit_Dzielnica': [,],
    # 'Cena/m2_mean_podzielnica': [,],
    # 'maksymalna_cena_podzielnica': [,],
    # 'additional_profit_podzielnica': [,]
}
